// <auto-generated />
using System;
using DiaryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiaryApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250720100013_insertDataDiaryEntry")]
    partial class insertDataDiaryEntry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DiaryApp.Models.DiaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DiaryEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Hello Dummy content 1",
                            CreatedAt = new DateTime(2025, 7, 20, 15, 22, 30, 0, DateTimeKind.Unspecified),
                            Title = "Dummy title 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Hello Dummy content 2",
                            CreatedAt = new DateTime(2025, 7, 20, 15, 23, 30, 0, DateTimeKind.Unspecified),
                            Title = "Dummy title 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Hello Dummy Content 3",
                            CreatedAt = new DateTime(2025, 7, 20, 15, 24, 30, 0, DateTimeKind.Unspecified),
                            Title = "Dummy title 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
